version: '3'

volumes:
  production_postgres_data: {}
  django-static: {}
  django-media: {}

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: proyecto_production_nginx
    volumes:
      - django-static:/usr/src/app/static
      - django-media:/usr/src/app/media
    depends_on:
      - django
    ports:
      - '80:80'

  django: &django
    build:
      context: ./backend
      dockerfile: compose/django/production/Dockerfile
    image: proyecto_production_django
    depends_on:
      - postgres
    env_file:
      - ./backend/.envs/.production/.django
      - ./backend/.envs/.production/.postgres
    volumes:
      - django-static:/app/static
      - django-media:/app/media
    command: /start

  postgres:
    build:
      context: ./backend
      dockerfile: compose/postgres/Dockerfile
    image: proyecto_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - ./backend/.envs/.production/.postgres

  redis:
    image: redis:3.2
    
  celeryworker:
    <<: *django
    image: bita_backend_production_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: bita_backend_production_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat


