# Generated by Django 3.0.8 on 2020-07-22 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(blank=True, max_length=240, null=True)),
                ('icono', models.CharField(blank=True, max_length=240, null=True)),
                ('ruta', models.CharField(blank=True, max_length=240, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(help_text='Nombre', max_length=255)),
                ('año', models.IntegerField(blank=True, null=True)),
                ('duracion', models.CharField(blank=True, help_text='duracion', max_length=255, null=True)),
                ('sinopsis', models.TextField(blank=True, help_text='duracion', null=True)),
                ('reparto', models.CharField(blank=True, help_text='duracion', max_length=255, null=True)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='bita_archivos')),
                ('triller', models.TextField(blank=True, help_text='duracion', null=True)),
                ('ruta', models.CharField(blank=True, max_length=240, null=True)),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelicula_created', related_query_name='peliculas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pelicula_update', related_query_name='peliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principal_peliculas',
                'ordering': ['-created', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='MenuPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Menu')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pelicula')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menupelicula_created', related_query_name='menupeliculas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menupelicula_update', related_query_name='menupeliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principal_menus_peliculas',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_pelicula',
            field=models.ManyToManyField(through='principal.MenuPelicula', to='principal.Pelicula'),
        ),
        migrations.AddField(
            model_name='menu',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_created', related_query_name='menus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menu',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_update', related_query_name='menus', to=settings.AUTH_USER_MODEL),
        ),
    ]
