# Generated by Django 3.0.8 on 2020-07-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(default=1, help_text='Titulo', max_length=255),
            preserve_default=False,
        ),
    ]
