# Generated by Django 3.0.8 on 2020-07-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_pelicula_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='nombre',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='subtitulo',
            field=models.CharField(default=1, help_text='subtitulo', max_length=255),
            preserve_default=False,
        ),
    ]
