# Generated by Django 3.0.8 on 2020-07-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_imagenesmuestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ruta',
            field=models.CharField(blank=True, choices=[('1', 'home'), ('2', 'MenusAdministrar'), ('3', 'no administrar')], default='2', max_length=240, null=True),
        ),
    ]
