# Generated by Django 3.0.8 on 2020-07-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20200724_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icono',
            field=models.CharField(blank=True, default='local_movies', max_length=240, null=True),
        ),
    ]
