# Generated by Django 3.0.8 on 2020-07-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20200724_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ruta',
            field=models.CharField(blank=True, choices=[('home', 'home'), ('MenusAdministrar', 'MenusAdministrar')], default='2', max_length=240, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='ruta',
            field=models.CharField(blank=True, choices=[('PeliculasDetalle', 'PeliculasDetalle')], default='1', max_length=240, null=True),
        ),
    ]
