# Generated by Django 3.0.8 on 2020-07-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0012_auto_20200724_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='vistas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
