# Generated by Django 3.0.8 on 2020-07-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0013_auto_20200724_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='reparto',
            field=models.CharField(blank=True, help_text='reparto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='sinopsis',
            field=models.TextField(blank=True, help_text='sinopsis', null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='triller',
            field=models.TextField(blank=True, help_text='triller', null=True),
        ),
    ]
