# Generated by Django 3.0.8 on 2020-07-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0018_imagenesmuestra_pelicula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Busqueda',
        ),
    ]
