# Generated by Django 3.0.8 on 2020-07-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0019_delete_busqueda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesmuestra',
            name='pelicula',
        ),
    ]
