# Generated by Django 3.0.8 on 2020-07-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_busqueda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenesMuestra',
        ),
    ]
