# Generated by Django 3.0.8 on 2020-07-31 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0024_auto_20200730_0451'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='link',
            field=models.TextField(blank=True, help_text='triller', null=True),
        ),
    ]
