# Generated by Django 3.0.8 on 2020-07-31 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_pelicula_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='link',
            field=models.TextField(blank=True, help_text='link del embed', null=True),
        ),
    ]
