# Generated by Django 3.0.8 on 2020-07-31 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0026_auto_20200731_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('nombre', models.CharField(blank=True, max_length=240, null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServidorPelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('delete', models.DateTimeField(blank=True, default=None, help_text='Date time on which the object was last delete.', null=True, verbose_name='delete at')),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_pelicula', to='principal.Pelicula')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_servidor', to='principal.Servidor')),
                ('uc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidorpelicula_created', related_query_name='servidorpeliculas', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidorpelicula_update', related_query_name='servidorpeliculas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'principal_servidores_peliculas',
            },
        ),
        migrations.AddField(
            model_name='servidor',
            name='servidor_pelicula',
            field=models.ManyToManyField(through='principal.ServidorPelicula', to='principal.Pelicula'),
        ),
        migrations.AddField(
            model_name='servidor',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor_created', related_query_name='servidors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servidor',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servidor_update', related_query_name='servidors', to=settings.AUTH_USER_MODEL),
        ),
    ]
