# Generated by Django 3.0.8 on 2020-07-31 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_auto_20200731_0310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servidor',
            options={'ordering': ['-created', '-modified']},
        ),
        migrations.AlterModelTable(
            name='servidor',
            table='principal_servidores',
        ),
    ]
