# Generated by Django 3.0.8 on 2020-07-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0029_auto_20200731_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='menupelicula',
            name='vistas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
